title: Daichao Qian's Homepage
page-top-title: Daichao Qian
top-section-bg-text: Charles Qian - Embodied AI & Robotics
home-subtitle: Daichao Qian&ensp;|&ensp;钱代超
copyright-text: '&copy; Daichao Qian 2025-2026. All Rights Reserved.'
